# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "UXofProducts"
description: > # this means to ignore newlines until "email:"
   UXofProducts is a review blog where I will be reviewing the user experience of various products. These products will be reviewed on overall ease of use, adherence to heuristics, information architecture, interaction designs, typography, visual language and design. I might also conduct user testing of these products to see how they fit ocassionally. This is my new exercise, hopefully you will have fun reading about it as much as I do reviewing products.

email: 
#blog logo
logo: "/assets/images/uxop.png"
# blog cover
cover: "/assets/images/teawriting.jpg"

name: 'TheUXMonkey'
author: 'Dee Nayak'
author_image: "/assets/images/author.png"

paginate:	5

url: "http://uxofproducts.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/theuxmonkey
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/dpnyk
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
